apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
  labels:
    app: transaction-service
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "tx-role"
        vault.hashicorp.com/agent-inject-secret-config: "secureflow/data/transaction-service"
    spec:
      serviceAccountName: transaction-sa
      containers:
        - name: transaction-service
          image: secureflow/transaction-service:v1 # CK-06 remediated
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          # envFrom:
          #   - configMapRef:
          #       name: secureflow-config
          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
            - name: DB_USER
              value: txuser
            # - name: DB_PASSWORD
            #   valueFrom:
            #     configMapKeyRef:
            #       name: secureflow-config
            #       key: TX_DB_PASSWORD
          securityContext:
            privileged: false                # CK-04
            allowPrivilegeEscalation: false  # CK-04
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          # CK-05 — no resources remediated.
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"                  
          
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002
