name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:

  # ---------------------------
  # STAGE 1 — SECRETS (HARD FAIL)
  # ---------------------------
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --log-opts="--all"


  # ---------------------------
  # STAGE 2 — CODE ANALYSIS (SOFT FAIL)
  # ---------------------------
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: gitleaks
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # ---------------------------
  # STAGE 3 — CONTAINER SCAN (HARD FAIL)
  # ---------------------------
  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: gitleaks
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'python:3.9-slim'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'